# Generated by Django 3.2.5 on 2021-07-14 00:43

import api.enums
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ZillowInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zillow_id', models.IntegerField()),
                ('last_sold_date', models.DateTimeField(null=True)),
                ('last_sold_price', models.IntegerField(null=True)),
                ('_link', models.SlugField()),
                ('rent_price', models.IntegerField(null=True)),
                ('rent_estimate_price', models.IntegerField(help_text='zillow own estimation for the monthly rent price', null=True)),
                ('rent_estimate_price_last_updated', models.DateTimeField(null=True)),
                ('price', models.IntegerField()),
                ('price_estimate', models.IntegerField(help_text='zillow own estimation for the price', null=True)),
                ('price_estimate_last_updated', models.DateTimeField(null=True)),
                ('tax_value', models.IntegerField()),
                ('tax_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_bathrooms', models.FloatField(null=True)),
                ('n_bedrooms', models.IntegerField()),
                ('home_size', models.IntegerField(help_text='the home size measures in square feet', null=True)),
                ('property_size', models.IntegerField(help_text='the whole property size measures in square feet', null=True)),
                ('home_type', models.CharField(choices=[(api.enums.HouseType['SingleFamily'], api.enums.HouseType['SingleFamily']), (api.enums.HouseType['VacantResidentialLand'], api.enums.HouseType['VacantResidentialLand']), (api.enums.HouseType['Condominium'], api.enums.HouseType['Condominium']), (api.enums.HouseType['MultiFamily2To4'], api.enums.HouseType['MultiFamily2To4']), (api.enums.HouseType['Duplex'], api.enums.HouseType['Duplex']), (api.enums.HouseType['Apartment'], api.enums.HouseType['Apartment'])], max_length=30)),
                ('year_built', models.IntegerField(null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.address')),
                ('zillow_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.zillowinfo')),
            ],
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['state', 'zipcode'], name='api_address_state_14b02b_idx'),
        ),
        migrations.AddIndex(
            model_name='home',
            index=models.Index(fields=['year_built'], name='api_home_year_bu_8be6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='home',
            index=models.Index(fields=['home_size'], name='api_home_home_si_1bf56c_idx'),
        ),
        migrations.AddIndex(
            model_name='home',
            index=models.Index(fields=['property_size'], name='api_home_propert_2ba392_idx'),
        ),
    ]
